### DISCUSSION TITLE
v7 CSS targeting of scrollbar

### DISCUSSION THREAD

**Discussion by jgentes** [katspaugh/wavesurfer.js#2798] [Q&A]
Now that we have a Shadow DOM, I haven't been able to figure out how to target the scrollbar. I see that there are predefined classes with targeting that exist:

```css
        :host .noScrollbar {
          scrollbar-color: transparent;
          scrollbar-width: none;
        }
        :host .noScrollbar::-webkit-scrollbar {
          display: none;
          -webkit-appearance: none;
        }
        :host .wrapper {
          position: relative;
          overflow: visible;
          z-index: 2;
        }
```
However if I do something like this:
```css
    '#waveform ::part(scroll)': {

      '&::webkit-scrollbar': {
        backgroundColor: 'green'
    }
```

That doesn't seem to have an affect, whereas it did work for the previous version.

Any ideas?

https://wavesurfer.pages.dev/examples/#styling.js
