### DISCUSSION TITLE
Region Text Bounds

### DISCUSSION THREAD

**Discussion by Lowgy** [katspaugh/wavesurfer.js#3991] [Q&A] [answered]
Is there a way to confine the region text to not extend outside of the region when resizing to a smaller duration?

**Comment by katspaugh** [comment, marked as answer]
You can contain it with one or all of these custom styles:

```css
      #your-container ::part(region) {
        overflow: auto;
        hyphens: auto;
        word-break: break-word;
      }
```

See https://wavesurfer.xyz/examples/?styling.js
