### DISCUSSION TITLE
Set waveform color through CSS

### DISCUSSION THREAD

**Discussion by jestin-g** [katspaugh/wavesurfer.js#4071] [Q&A] [answered]
Hello, my question is pretty straight forward:
Is it possible to set the waveform color with CSS ?

For example I have this code:

```css
  #wavesurfer ::part(progress) {
    background-color: red; // work
    color: blue; // don't work
  }
```

Giving me this:
![image](https://github.com/user-attachments/assets/10735691-3b4a-4efe-a723-c0b799873773)

I assume that my code is wrong but is there a way to style the waveform itself?

That would greatly help me because my app is themed through css variables.

Thanks!
