### ISSUE TITLE
Customize the style of the scrollbar

### ISSUE THREAD

**Issue by massis08** [katspaugh/wavesurfer.js#2200]
Hi! 

I would like to know if it is possible to customize the style of the scrollbar present in the waveform.
Or if it is possible to use a custom scrollbar, as this one for example: https://github.com/malte-wessel/react-custom-scrollbars

Thank you

**Comment by entonbiba** [comment]
Here you go:

https://www.entonbiba.com/lab/wavesurfer/2200.html

``` css
	wave {
	  scrollbar-width: thin;
	  scrollbar-color: #eee;
	}

	wave::-webkit-scrollbar {
	  width: 5px;
	  height:10px;
	}

	wave::-webkit-scrollbar-track {
	  background: #eee;
	}

	wave::-webkit-scrollbar-thumb {
	  background-color: #444;
	  border-radius: 5px;
	  border: 2px solid #ddd;
	}
```

![image](https://user-images.githubusercontent.com/5193884/110054147-92ccef00-7d28-11eb-895a-bfa63f2945d1.png)
