### ISSUE TITLE
CSP set to nonce, <style nonce="QWHzeTLwpGPwTNySpBKyHH8k"> not set

### ISSUE THREAD

**Issue by PaulHendriks** [katspaugh/wavesurfer.js#3602]
## Bug description
If CSP policy is strict and requires a nonce, the generated <style> block wont work

## Environment
 - Browser: Firefox

## Minimal code snippet
Content-Security-Policy | script-src 'nonce-bTFivopG26dOZPgqLdM1Yg27'; style-src 'nonce-QWHzeTLwpGPwTNySpBKyHH8k'

## Expected result
<style nonce="QWHzeTLwpGPwTNySpBKyHH8k">
        :host {
          user-select: none;
          min-width: 1px;
        }
...
</style>

Or a seperate .css file would also work.

## Obtained result
<style>
        :host {
          user-select: none;
          min-width: 1px;
        }

## Screenshots
![afbeelding](https://github.com/katspaugh/wavesurfer.js/assets/17846767/8c1fd81a-2422-4150-a24e-f3a734e09bad)

**Comment by katspaugh** [comment]
I think that’s quite an edge case but pull requests are welcome.

**Comment by PaulHendriks** [comment]
Not sure how to fix this.. if i hack a nonce attribute into the `<style>` tag, it will render empty. Likewise, the browser wont let me read the nonce attribute of a `<link rel="stylesheet" nonce="something">` tag. The last part i can work around, but not the first part.
Neither can i get the `<style>` tag after it's rendered, probably because of the CSP setting.

Is the `<style>` tag necessary because of computed dimensions?

**Comment by katspaugh** [comment]
I think I did it this way mostly to just keep everything in JS and make it less complicated for people to import/host. In theory, it could be a static external CSS file, and dynamic styles could be added directly to the corresponding elements.

**Comment by PaulHendriks** [comment]
I've added this to my stylesheet, but that doesn't solve the issue:
```css
:host {
  user-select: none;
  min-width: 1px;
}
:host audio {
  display: block;
  width: 100%;
}
:host .scroll {
  overflow-x: auto;
  overflow-y: hidden;
  width: 100%;
  position: relative;
}
:host .noScrollbar {
  scrollbar-color: transparent;
  scrollbar-width: none;
}
:host .noScrollbar::-webkit-scrollbar {
  display: none;
  -webkit-appearance: none;
}
:host .wrapper {
  position: relative;
  overflow: visible;
  z-index: 2;
}
:host .canvases {
  min-height: 128px;
}
:host .canvases > div {
  position: relative;
}
:host canvas {
  display: block;
  position: absolute;
  top: 0;
  image-rendering: pixelated;
}
:host .progress {
  pointer-events: none;
  position: absolute;
  z-index: 2;
  top: 0;
  left: 0;
  width: 0;
  height: 100%;
  overflow: hidden;
}
:host .progress > div {
  position: relative;
}
:host .cursor {
  pointer-events: none;
  position: absolute;
  z-index: 5;
  top: 0;
  left: 0;
  height: 100%;
  border-radius: 2px;
}
```

I've tried adding a selector  `:host(.waveform)` but that doesn't work neither.
What should the static css file look like?
