### ISSUE TITLE
Render Waveform Like Soundcloud.

### ISSUE THREAD

**Issue by interwap** [katspaugh/wavesurfer.js#938]
Hello Katspaugh, great working you got going here with the wavesuferjs plugin. Huge fan!!!

I like way wavesurfer renders the waves tho. Its elegant but is it possible to render the waves like the way soundcloud does. The waveform on soundcloud is bunkers and i really like.

If it's doable, i'd really like to know how using the default wavesurfer.min.js configuration. 

Thanks

**Comment by entonbiba** [comment]
@interwap there will be a parameter option to apply the soundcloud wave in this pr, #1024

**Comment by interwap** [comment]
@entonbiba great, looking forward to it. Just read through the conversation

**Comment by thijstriemstra** [comment]
can a screenshot of the soundcloud waveform be attached?

**Comment by delewis13** [comment]
@entonbiba was this ever added / does it still exist? If not, do you have any pointers on what to edit in a custom renderer to achieve this effect? Cheers :)

**Comment by entonbiba** [comment]
@delewis13 I added the barHeight option a while ago, however the soundcloud wav design thing would look like the following with a simple div overlay that is transparent. I'll link to a sample in a few minutes.

![image](https://user-images.githubusercontent.com/5193884/105647222-1403ad00-5e72-11eb-9872-38d97445a8e1.png)

![image](https://user-images.githubusercontent.com/5193884/105647223-1a922480-5e72-11eb-860d-add86b270ad4.png)


``` css
.overlayBar{
    height: 55px; // would be based on half the size of the rendered wavesurfer element
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    z-index: 2;
    background: rgba(255,255,255,0.1);
}
.waveformBar wave{
   z-index:1;
}
```
```
<div id="waveform">
    <div class="overlayBar></div>
    <wave></wave>
</div>
```
